### ISSUE TITLE
No module named fritzbox

### ISSUE THREAD

**Issue by Wallmeier** [twam/fritzbox2mqtt#1]
Hi!

I've installed all mentioned requirements from requirements.txt. If I try to execute fritzbox2mqtt.py I get the following error message:
```python 
python fritzbox2mqtt.py
Traceback (most recent call last):
  File "fritzbox2mqtt.py", line 12, in <module>
    import fritzbox
ImportError: No module named fritzbox
```

Is the file fritzbox.py missing in the repository?

Kind regards,
Nico Wallmeier

**Comment by twam** [comment]
You're right! `fritzbox.py` was missing. I added it.
